#!/bin/bash

# Bundle ID Verification and App Store Connect Setup
echo "🔍 Bundle ID and App Store Connect Verification"
echo "=============================================="

BUNDLE_ID="com.knoxweb.miin-ojibwe"
echo "📋 Your app's Bundle ID: $BUNDLE_ID"

echo ""
echo "🚨 CRITICAL: The #1 reason builds don't appear in TestFlight:"
echo "============================================================"
echo "❌ The Bundle ID doesn't exist in App Store Connect"
echo ""
echo "🔍 PLEASE VERIFY IN APP STORE CONNECT:"
echo "======================================"
echo "1. 🌐 Go to: https://appstoreconnect.apple.com"
echo "2. 📱 Click 'My Apps'"
echo "3. 🔍 Look for an app with Bundle ID: $BUNDLE_ID"
echo ""
echo "IF THE APP DOESN'T EXIST:"
echo "========================"
echo "You MUST create the app in App Store Connect FIRST:"
echo "1. 📱 Click the '+' button in My Apps"
echo "2. 🆕 Select 'New App'"
echo "3. 📝 Fill in:"
echo "   • Name: MIIN-Ojibwe"
echo "   • Bundle ID: $BUNDLE_ID"
echo "   • Primary Language: English"
echo "4. ✅ Click 'Create'"
echo ""
echo "ONLY THEN can you upload builds to TestFlight!"

echo ""
echo "🔧 IF THE APP EXISTS BUT BUILDS STILL DON'T APPEAR:"
echo "=================================================="
echo "1. 📧 Check your email (Apple Developer account email)"
echo "2. 🔍 In App Store Connect > TestFlight, check:"
echo "   • iOS Builds tab"
echo "   • Missing Compliance tab"
echo "   • Processing status"
echo "3. 🔄 Try the alternative upload method below"

echo ""
echo "🛠️  ALTERNATIVE UPLOAD METHOD (More Reliable):"
echo "=============================================="
echo "Instead of Xcode's Distribute App:"
echo "1. 📦 Archive the app (Product > Archive)"
echo "2. 📤 In Organizer, select your archive"
echo "3. 🔄 Click 'Distribute App'"
echo "4. 📱 Select 'App Store Connect'"
echo "5. 📋 Select 'Export' (NOT Upload)"
echo "6. 💾 Save the .ipa file to Desktop"
echo "7. 🌐 Go to App Store Connect manually"
echo "8. 📱 Go to your app > TestFlight"
echo "9. ➕ Click the '+' next to iOS builds"
echo "10. 📁 Select your .ipa file"
echo "11. ⬆️  Upload manually"

echo ""
echo "📱 Quick App Store Connect Links:"
echo "================================"
echo "• Main: https://appstoreconnect.apple.com"
echo "• My Apps: https://appstoreconnect.apple.com/apps"
echo "• Create App: https://appstoreconnect.apple.com/apps/new"

echo ""
echo "✨ Next Steps:"
echo "============="
echo "1. ✅ Verify the app exists in App Store Connect"
echo "2. ✅ If not, create it with Bundle ID: $BUNDLE_ID"
echo "3. ✅ Try the manual .ipa upload method"
echo "4. ✅ Check email for any rejection reasons"

echo ""
echo "💡 Pro Tip: The app MUST exist in App Store Connect"
echo "   before any builds will appear in TestFlight!"
